using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ElliotDvp_tarea04.Models;

namespace ElliotDvp_tarea04.Controllers;

public class ListaController : Controller
    {
        public bool MostrarModal { get; set; } = false; // Inicialmente oculto
        private static List<Lista> perros = Enumerable.Range(1, 100).Select(i => new Lista
    {
        Nombre = $"Perro {i}",
        Peso = $"{10 + (i % 20)} kg",
        Tamano = (i % 2 == 0) ? "Grande" : "Pequeño",
        Edad = $"{2 + (i % 10)} años",
        Descripcion = $"Descripción del perro {i}.",
        Categoria = (i % 5) switch
        {
            0 => "Perros pequeños",
            1 => "Perros familiares",
            2 => "Perros raros",
            3 => "Perros guardianes",
            _ => "Perros para apartamento"
        }
    }).ToList();

         public IActionResult Index()
    {
        var perros = new List<Lista>
        {
        new Lista { Nombre = "Airedale Terrier", Peso = "20 kg", Tamano = "Mediano", Edad = "8 años", Descripcion = "Terrier inglés activo y valiente.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7WAOUY0HUOG_ZZnViGcCeNfEf79psMFxdEQ&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Akita Inu", Peso = "35 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Leal y protector, originario de Japón.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Akita_Inu_%28male%29.jpg/1200px-Akita_Inu_%28male%29.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Alaskan Malamute", Peso = "38 kg", Tamano = "Grande", Edad = "9 años", Descripcion = "Fuerte perro de trineo del Ártico.", ImagenUrl = "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/09151144/Alaskan-Malamute-standing-in-the-grass1.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "American Bully", Peso = "30 kg", Tamano = "Mediano", Edad = "8 años", Descripcion = "Musculoso y cariñoso.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Champion_Charlie_Muscles_%282%29.jpg/960px-Champion_Charlie_Muscles_%282%29.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "American Pit Bull Terrier", Peso = "27 kg", Tamano = "Mediano", Edad = "9 años", Descripcion = "Ágil y energético.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/b/b0/001_American_Pit_Bull_Terrier.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Basenji", Peso = "10 kg", Tamano = "Pequeño", Edad = "12 años", Descripcion = "Perro africano que no ladra.", ImagenUrl = "https://eyracan.com/wp-content/uploads/2023/10/raza-de-perro-basenji.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Beagle", Peso = "11 kg", Tamano = "Pequeño", Edad = "13 años", Descripcion = "Sociable y amigable.", ImagenUrl = "https://cdn.britannica.com/16/234216-050-C66F8665/beagle-hound-dog.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Bichón Frisé", Peso = "6 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Blanco y esponjoso.", ImagenUrl = "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/UEWI2YAQABEUFBDT67HEHTCH6M.jpg", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Bloodhound", Peso = "36 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Experto rastreador.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzA39ASfSfgsw_LmH2yuTM7qZm2PM4cu0obw&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Bobtail", Peso = "32 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Pastor inglés de pelo largo.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM0L7MpKE5C4m4PKi2ly1UKW62HlSteqQt_w&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Border Collie", Peso = "20 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "El perro más inteligente del mundo.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Border_collie_canon.jpg/330px-Border_collie_canon.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Boston Terrier", Peso = "7 kg", Tamano = "Pequeño", Edad = "13 años", Descripcion = "Americano de carácter alegre.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/6/66/BostonTerrierBrindleStand_w.jpg", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Boxer", Peso = "30 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Energético y juguetón.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfcNEk_AYJ1ZGbC_SRLsmXvWnnD376hlzwuA&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Bulldog Francés", Peso = "12 kg", Tamano = "Pequeño", Edad = "10 años", Descripcion = "Cariñoso y de orejas de murciélago.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC_H4rfKaC2zOvT0a0MfYk9Lr0QYQyKaIuVg&s", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Bulldog Inglés", Peso = "25 kg", Tamano = "Mediano", Edad = "8 años", Descripcion = "Tierno y tranquilo.", ImagenUrl = "https://www.zooplus.es/magazine/wp-content/uploads/2017/10/fotolia_58776564.webp", Categoria = "Perros familiares" },
        new Lista { Nombre = "Bullmastiff", Peso = "50 kg", Tamano = "Grande", Edad = "9 años", Descripcion = "Protector y valiente.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1cIr6s-8D3Loc9lkF9HS_KPRjSouF9osYVQ&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Cairn Terrier", Peso = "6 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Valiente y alerta.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Cairn-Terrier-Garten1.jpg/1200px-Cairn-Terrier-Garten1.jpg", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Caniche Toy", Peso = "4 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Inteligente y elegante.", ImagenUrl = "https://cdn.shopify.com/s/files/1/0648/0124/3361/files/iStock-1380984414.jpg?v=1741704029", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Carlino", Peso = "8 kg", Tamano = "Pequeño", Edad = "13 años", Descripcion = "Cariñoso y de expresión dulce.", ImagenUrl = "https://www.purina.es/sites/default/files/styles/ttt_image_510/public/2024-02/sitesdefaultfilesstylessquare_medium_440x440public2022-08Pug.jpg?itok=6_9mk7Br", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Chihuahua", Peso = "3 kg", Tamano = "Pequeño", Edad = "15 años", Descripcion = "El perro más pequeño del mundo.", ImagenUrl = "https://cdn.britannica.com/44/233244-050-A65D4571/Chihuahua-dog.jpg", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Chow Chow", Peso = "25 kg", Tamano = "Mediano", Edad = "11 años", Descripcion = "De lengua azul y carácter independiente.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAYGKNyQ2vtsETXh6fnQ1OcmTULmCi4BfbGQ&s", Categoria = "Perros raros" },
        new Lista { Nombre = "Cocker Spaniel", Peso = "13 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Alegre y de orejas largas.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a0/English_Cocker_Simon_Left.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Collie", Peso = "25 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Elegante y leal.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/1Dog-rough-collie-portrait.jpg/330px-1Dog-rough-collie-portrait.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Dálmata", Peso = "25 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Famoso por sus manchas.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/f/fe/Dalmatien.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Doberman", Peso = "35 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Ágil y protector.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/3/3f/Dobermann_Father-and-son.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Dogo Argentino", Peso = "45 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Fuerte y valiente.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Argentine_Dogo_%28535032632%29_%28cropped%29.jpg/960px-Argentine_Dogo_%28535032632%29_%28cropped%29.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Fox Terrier", Peso = "8 kg", Tamano = "Pequeño", Edad = "13 años", Descripcion = "Energético y curioso.", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/wirehaired-fox-terrier-dog-breed-full-body.webp", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Golden Retriever", Peso = "32 kg", Tamano = "Grande", Edad = "11 años", Descripcion = "Amigable y paciente.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMujS15SM16Qj2uDh6Zj9DZ2K0KjPMH6C6kA&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Gran Danés", Peso = "70 kg", Tamano = "Gigante", Edad = "7 años", Descripcion = "El Apolo de los perros.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-BiQXteR-leItNtP7NiZ91MyktkwhLzbrMg&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Husky Siberiano", Peso = "25 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "De ojos azules y espíritu libre.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8FwNbH7eaZFGIP8OOb1WC18J5PH6j_Kjr0Q&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Jack Russell Terrier", Peso = "6 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Energético y valiente.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Jack_Russell_Terrier_1.jpg/330px-Jack_Russell_Terrier_1.jpg", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Labrador Retriever", Peso = "30 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "El perro más popular del mundo.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Labrador_Retriever_%281210559%29.jpg/1200px-Labrador_Retriever_%281210559%29.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Lhasa Apso", Peso = "7 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Tibetano de pelo largo.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToaowkGeor1wSVsqF3UGJofdoPVTVwzJpojQ&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Papillón", Peso = "4 kg", Tamano = "Pequeño", Edad = "15 años", Descripcion = "Elegante y afectuoso.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzZYjCF5chqaw9H03cQZMzXDlXX5zdHHADcg&s", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Mastín Español", Peso = "60 kg", Tamano = "Gigante", Edad = "10 años", Descripcion = "Poderoso y tranquilo.", ImagenUrl = "https://www.consumer.es/app/uploads/2024/01/mastin1.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Pastor Alemán", Peso = "35 kg", Tamano = "Grande", Edad = "11 años", Descripcion = "Inteligente y versátil.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Cane_da_pastore_tedesco_adulto.jpg/330px-Cane_da_pastore_tedesco_adulto.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Pequinés", Peso = "5 kg", Tamano = "Pequeño", Edad = "13 años", Descripcion = "Pequeño y valiente.", ImagenUrl = "https://www.patasencasa.com/sites/default/files/styles/article_detail_1200/public/2023-10/pequenês.jpg.webp?itok=qe5vnWiD", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Pomerania", Peso = "3 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Pequeño y esponjoso.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf44mdBBigEeP3gOMaR99u1zkVlsQbV__i9Q&s", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Pug", Peso = "8 kg", Tamano = "Pequeño", Edad = "13 años", Descripcion = "Cariñoso y de expresión dulce.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkm4TAN74xbBa4TdjYVgxBlprhFNjp5WDQaw&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Rottweiler", Peso = "45 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Protector y leal.", ImagenUrl = "https://www.purina.es/sites/default/files/styles/ttt_image_510/public/2024-02/sitesdefaultfilesstylessquare_medium_440x440public2022-08Rottweiler2.jpg?itok=7k9LOIq0", Categoria = "Perros guardianes" },
        new Lista { Nombre = "San Bernardo", Peso = "80 kg", Tamano = "Gigante", Edad = "8 años", Descripcion = "Rescatador alpino.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Rey_nieve.jpg/330px-Rey_nieve.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Schnauzer Miniatura", Peso = "7 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Inteligente y alerta.", ImagenUrl = "https://www.purina.es/sites/default/files/styles/ttt_image_510/public/2024-02/sitesdefaultfilesstylessquare_medium_440x440public2022-09Schnauzer2028Miniature29.jpg?itok=yyCDqukh", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Shar Pei", Peso = "22 kg", Tamano = "Mediano", Edad = "10 años", Descripcion = "De piel arrugada.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/b/be/Minnie_waja.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Shiba Inu", Peso = "10 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Japonés de carácter independiente.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRplJugLLMsJ6yUidL0rpM0xkeB9DPm2tgLow&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Shih Tzu", Peso = "6 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Cariñoso y de pelo largo.", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2025/02/maltese-shih-tzu-close-up-in-garden.webp", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Terranova", Peso = "60 kg", Tamano = "Gigante", Edad = "9 años", Descripcion = "Excelente nadador.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/5/5c/Bearb_josh04_07.JPG", Categoria = "Perros familiares" },
        new Lista { Nombre = "West Highland White Terrier", Peso = "8 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Blanco y alegre.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC7cg5BTmWhGlbWfyjSBgLviRCQ5BB_P6Gdw&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Yorkshire Terrier", Peso = "3 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Pequeño y valiente.", ImagenUrl = "https://www.purina.es/sites/default/files/styles/ttt_image_510/public/2024-02/sitesdefaultfilesstylessquare_medium_440x440public2022-09Yorkshire20Terrier.jpg?itok=MQRiTY3f", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Affenpinscher", Peso = "4 kg", Tamano = "Pequeño", Edad = "12 años", Descripcion = "Pequeño y de expresión simiesca.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkNZhpW06tNfh2kukzMtVHvfaREhM1JP5P3w&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Afghan Hound", Peso = "27 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Elegante y de pelo largo.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/e/e8/Afghan_dog_-_cropped.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Aidi", Peso = "25 kg", Tamano = "Mediano", Edad = "11 años", Descripcion = "Perro de montaña marroquí.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/6/6a/Aidi_Atlas.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Azawakh", Peso = "20 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Lebrel africano esbelto.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Bistrita_2015_%2822%29.jpg/330px-Bistrita_2015_%2822%29.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Beauceron", Peso = "35 kg", Tamano = "Grande", Edad = "11 años", Descripcion = "Pastor francés inteligente.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/BeauceronStand.jpg/330px-BeauceronStand.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Bedlington Terrier", Peso = "10 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Parecido a un cordero.", ImagenUrl = "https://www.zooplus.es/magazine/wp-content/uploads/2023/05/Bedlington-terrier.webp", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Bergamasco", Peso = "32 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "De pelo en rastas.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/8/80/Bergamasco_600.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Bichón Maltés", Peso = "4 kg", Tamano = "Pequeño", Edad = "15 años", Descripcion = "Blanco y sedoso.", ImagenUrl = "https://centralpetsperu.com/wp-content/uploads/2021/11/Bichon-Maltes-1-800x800.png", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Borzoi", Peso = "40 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Lebrel ruso aristocrático.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXllktSfNERejoCzYYiLcGGvMTHFiZ8aBYEA&s", Categoria = "Perros raros" },
        new Lista { Nombre = "Boyero de Berna", Peso = "45 kg", Tamano = "Grande", Edad = "8 años", Descripcion = "Tricolor suizo.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Bernese_Mountain_DOg2.jpg/960px-Bernese_Mountain_DOg2.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Braco Alemán", Peso = "30 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Excelente perro de caza.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/3/38/Duitse_staande_korthaar_10-10-2.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Braco de Weimar", Peso = "35 kg", Tamano = "Grande", Edad = "11 años", Descripcion = "Elegante y de color gris.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Weimaraner_in_Tallinn_3.JPG/960px-Weimaraner_in_Tallinn_3.JPG", Categoria = "Perros familiares" },
        new Lista { Nombre = "Bull Terrier", Peso = "28 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "De cabeza ovalada característica.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQs2OpbaCd3zAjfjdZz_aB1yfuX2pPLa6ALMg&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Cane Corso", Peso = "45 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Moloso italiano poderoso.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d9/FINLEY_DE_LA_MIRAGE_DE_TORRELLAS_01.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Chesapeake Bay Retriever", Peso = "32 kg", Tamano = "Grande", Edad = "11 años", Descripcion = "Amante del agua.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSTGOlLgilS7g02RX3T57UM-gbOGyGNU7DSw&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Crestado Chino", Peso = "5 kg", Tamano = "Pequeño", Edad = "13 años", Descripcion = "Con o sin pelo.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/IndyStands.jpg/1200px-IndyStands.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Dogo de Burdeos", Peso = "50 kg", Tamano = "Grande", Edad = "9 años", Descripcion = "Moloso francés musculoso.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Dogo_de_Burdeos_.jpg/330px-Dogo_de_Burdeos_.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Elkhound Noruego", Peso = "22 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Perro vikingo resistente.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d4/Norwegian_Elkhound.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Galgo Español", Peso = "30 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Lebrel español veloz.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4FbcHzZiBOAWrkT1ez6xMEWz1JkS3PKg37A&s", Categoria = "Perros raros" },
        new Lista { Nombre = "Irish Wolfhound", Peso = "55 kg", Tamano = "Gigante", Edad = "7 años", Descripcion = "El perro más alto.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBeIIiVoOrNQKLSopRUkrCsz-NGH-Q8bX87Q&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Keeshond", Peso = "18 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "Esponjoso y simpático.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDQ8EUwvc56V4remOBq3NrKpSTCwFjmefXgA&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Kerry Blue Terrier", Peso = "18 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "De pelaje azulado.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Kerry_Blue_Terrier.jpg/960px-Kerry_Blue_Terrier.jpg", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Komondor", Peso = "50 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Parecido a una fregona.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Komondor_Westminster_Dog_Show_crop.jpg/330px-Komondor_Westminster_Dog_Show_crop.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Kuvasz", Peso = "45 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Pastor húngaro blanco.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/c/ca/Grupp_1%2C_KUVASZ%2C_FI_UCH_NO_UCH_SE_UCH_WW-14_Czaruso_Brian_Little_%2823681983424%29.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Leonberger", Peso = "65 kg", Tamano = "Gigante", Edad = "8 años", Descripcion = "Gentil gigante alemán.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Leonberger_male.jpg/330px-Leonberger_male.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Löwchen", Peso = "5 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Pequeño león.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiIdvY4YIfpIdT-mtf2bHNzY0s_Ukwwddvmg&s", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Perro de Agua Español", Peso = "20 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "De pelo rizado.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1qiR8VqhOLgamDus2ZVxYvgAakcU5HwYe2A&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Perro sin Pelo del Perú", Peso = "12 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "Sin pelo y elegante.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Perro_Sin_Pelo_del_Perú.jpg/1200px-Perro_Sin_Pelo_del_Perú.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Pharaoh Hound", Peso = "20 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Lebrel maltés antiguo.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7a41A0pdqvyjv7HJnI4vxWlHBIyFAx_rPZQ&s", Categoria = "Perros raros" },
        new Lista { Nombre = "Pointer", Peso = "25 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Elegante perro de caza.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/English_pointer.jpg/1200px-English_pointer.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Presa Canario", Peso = "50 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Moloso de las Islas Canarias.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Presa_Canario.jpg/1200px-Presa_Canario.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Pudelpointer", Peso = "30 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Cruza de caniche y pointer.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgW5Z9_qckHiTbu7a0caHXa76fX5rAkXGWYg&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Rhodesian Ridgeback", Peso = "36 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Con cresta en la espalda.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Rhodesian_ridgeback.jpg/250px-Rhodesian_ridgeback.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Samoyedo", Peso = "25 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Blanco y sonriente.", ImagenUrl = "https://www.purina.es/sites/default/files/2021-02/BREED%20Hero_0110_samoyed.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Setter Irlandés", Peso = "32 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Pelirrojo y elegante.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/2/2e/Can_Setter_dog_GFDL.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Spaniel Tibetano", Peso = "5 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Pequeño y alerta.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjZm3tdGkodt1cfuAvBE-Zo44E6uSrOdSvHw&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Spitz Japonés", Peso = "10 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Blanco y esponjoso.", ImagenUrl = "https://content.elmueble.com/medio/2024/06/04/spitz-japones_9eed3194_1489388299_240604123251_900x900.jpg", Categoria = "Perros para apartamento" },
        new Lista { Nombre = "Staffordshire Bull Terrier", Peso = "17 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Musculoso y afectuoso.", ImagenUrl = "https://www.purina.es/sites/default/files/styles/ttt_image_510/public/2024-02/sitesdefaultfilesstylessquare_medium_440x440public2022-08Staffordshire20Bull20Terrier1.jpg?itok=dW47_tn_", Categoria = "Perros familiares" },
        new Lista { Nombre = "Teckel", Peso = "9 kg", Tamano = "Pequeño", Edad = "14 años", Descripcion = "Salchicha de patas cortas.", ImagenUrl = "https://images.ctfassets.net/550nf1gumh01/yh0l63Foctzv7067YDNhO/e391cd9ef39818a77484e5b1fd29f5bc/iStock-145053225.jpg?q=90&w=1240", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Vizsla", Peso = "25 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Húngaro de color dorado.", ImagenUrl = "https://www.dogpackapp.com/blog/wp-content/uploads/2024/11/vizsla-dog-standing-field.webp", Categoria = "Perros familiares" },
        new Lista { Nombre = "Xoloitzcuintle", Peso = "14 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "Perro azteca sin pelo.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR95fGnGqdZEw87aAQzG6rdicMZcEMbcmGs0g&s", Categoria = "Perros raros" },
        new Lista { Nombre = "Appenzeller", Peso = "25 kg", Tamano = "Mediano", Edad = "12 años", Descripcion = "Pastor suizo versátil.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvR-okvM_ZcW9Q-NSOOol7RKdj6EjZf1MLzQ&s", Categoria = "Perros familiares" },
        new Lista { Nombre = "Barbet", Peso = "20 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "De pelo rizado y acuático.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/c/cf/Chien_de_race_Barbet.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Cirneco del Etna", Peso = "12 kg", Tamano = "Mediano", Edad = "14 años", Descripcion = "Lebrel siciliano.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Cirneco_dell_Etna_611.jpg/640px-Cirneco_dell_Etna_611.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Drever", Peso = "15 kg", Tamano = "Pequeño", Edad = "12 años", Descripcion = "Cazador sueco.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnqvnUWmQhLHqJ65R9gWuEQfyXxdhRvHFUsA&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Eurasier", Peso = "23 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "Compañero alemán equilibrado.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/3/36/Eurasier_BailyWtatze.jpg", Categoria = "Perros familiares" },
        new Lista { Nombre = "Fila Brasileiro", Peso = "50 kg", Tamano = "Grande", Edad = "10 años", Descripcion = "Moloso brasileño protector.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ04FjvdGXCQjVJL_N6y0TpKUXykm8YtrjpeA&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Glen of Imaal Terrier", Peso = "16 kg", Tamano = "Pequeño", Edad = "12 años", Descripcion = "Terrier irlandés de patas cortas.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV-sLJtvHqcgE4nPzwHxLwffM-pnEc595B8Q&s", Categoria = "Perros pequeños" },
        new Lista { Nombre = "Hovawart", Peso = "40 kg", Tamano = "Grande", Edad = "12 años", Descripcion = "Guardián alemán versátil.", ImagenUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/The_three_colours_of_the_Hovawart.jpg/1200px-The_three_colours_of_the_Hovawart.jpg", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Jindo Coreano", Peso = "20 kg", Tamano = "Mediano", Edad = "13 años", Descripcion = "Leal y reservado.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnTCrM15PA8D3uflXOe8UgbXJ_rDmXl_ZOmQ&s", Categoria = "Perros guardianes" },
        new Lista { Nombre = "Kai Ken", Peso = "18 kg", Tamano = "Mediano", Edad = "14 años", Descripcion = "Tigre japonés.", ImagenUrl = "https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/04173549/Kai-Ken-standing-in-profile-outdoors.jpg", Categoria = "Perros raros" },
        new Lista { Nombre = "Lagotto Romagnolo", Peso = "16 kg", Tamano = "Mediano", Edad = "15 años", Descripcion = "Buscador de trufas italiano.", ImagenUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5wdn26-egWmXjmUojnXvPWN_QHayyOyHucQ&s", Categoria = "Perros familiares" }
        };

        return View(perros);
    }
    }
